//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication9.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPNHAT
    {
        public string MACN { get; set; }
        public string MAGDV { get; set; }
        public string MASTK { get; set; }
        public string MALOAITK { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public Nullable<double> SODU { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYDH { get; set; }
    
        public virtual GIAODICHVIEN GIAODICHVIEN { get; set; }
        public virtual LOAITK LOAITK { get; set; }
        public virtual STK STK { get; set; }
    }
}
