//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication9.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAODICH
    {
        public string SOGD { get; set; }
        public string MAGDV { get; set; }
        public string MAKH { get; set; }
        public string MAQUAYGD { get; set; }
        public Nullable<System.DateTime> NGAYGD { get; set; }
        public string CTGD { get; set; }
    
        public virtual GIAODICHVIEN GIAODICHVIEN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual QUAYGD QUAYGD { get; set; }
    }
}
