create database QuanLySoTietKiem

go
use QuanLySoTietKiem

go
create table STK
(
	MASTK char(10),
	MAKH char(10),
	MALOAITK char(10),
	NGAYMO	smalldatetime,
	NGAYBD smalldatetime,
	NGAYDH smalldatetime,
	SODU decimal,
	CONSTRAINT PK_STK_MASTK PRIMARY KEY (MASTK)
)

go
create table KHACHHANG
(
	MAKH char(10),
	HOTEN Varchar(40),
	DIACHI Varchar(40),
	SDT Varchar(20),
	GIOITINH nvarchar(3),
	NGAYSINH Smalldatetime,
	CMND Varchar(20),
	CONSTRAINT PK_KHACHHANG_MAKH PRIMARY KEY (MAKH)
)

go
create table GIAODICHVIEN
(
	MAGDV char(10),
	MAPHONG Char(10),
	HOTEN Varchar(40),
	DIACHI Varchar(40),
	SDT Varchar(20),
	GIOITINH nvarchar(3),
	NGAYSINH Smalldatetime,
	CMND Varchar(20),
	MATK Char(10),
	CONSTRAINT PK_GIAODICHVIEN_MAGDV PRIMARY KEY (MAGDV)
)

go
create table PHONGBAN
(
	MAPHONG char(10),
	DIADIEM Varchar(40),
	TRGPHONG Char(10),
	NGAYNC Smalldatetime,
	CONSTRAINT PK_PHONGBAN_MAPHONG PRIMARY KEY (MAPHONG)
)

go
create table QUAYGD
(
	MAQUAY char(10),
	TENQUAY varchar(100),
	CONSTRAINT PK_QUAYGD_MAQUAY PRIMARY KEY (MAQUAY)
)

go
create table LOAITK
(
	MALOAITK char(10),
	TENLOAI varchar(50),
	LAISUAT float,
	KIHAN varchar(50),
	CONSTRAINT PK_LOAITK_MALOAITK PRIMARY KEY (MALOAITK)
)

go
create table GIAODICH
(
	SOGD char(10),
	MAGDV char(10),
	MAKH char(10),
	MAQUAYGD char(10),
	NGAYGD smalldatetime,
	CTGD varchar(50),
	CONSTRAINT PK_GIAODICH_SOGD PRIMARY KEY (SOGD)
)

go
create table ACCOUNT
(
	MATK char(10),
	TAIKHOAN varchar(50),
	MATKHAU varchar(50),
	CONSTRAINT PK_TAIKHOAN_MATK PRIMARY KEY (MATK)
)

go
create table CAPNHAT
(
	MACN char(10),
	MAGDV Char(10),
	MASTK Char(10),
	MALOAITK Char(10),
	NGAYCN Smalldatetime,
	SODU decimal,
	NGAYBD smalldatetime,
	NGAYDH smalldatetime,
	CONSTRAINT PK_CAPNHAT_MACN PRIMARY KEY (MACN)
)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT FK_GIAODICHVIEN_PHONGBAN 
FOREIGN KEY (MAPHONG) 
REFERENCES PHONGBAN(MAPHONG)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT FK_GIAODICHVIEN_TAIKHOAN
FOREIGN KEY (MATK) 
REFERENCES ACCOUNT(MATK)

GO
ALTER TABLE PHONGBAN 
ADD CONSTRAINT FK_PHONGBAN_GIAODICHVIEN
FOREIGN KEY (TRGPHONG) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_GIAODICHVIEN
FOREIGN KEY (MAGDV) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_QUAYGD
FOREIGN KEY (MAQUAYGD) 
REFERENCES QUAYGD(MAQUAY)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_KHACHHANG
FOREIGN KEY (MAKH) 
REFERENCES KHACHHANG(MAKH)

GO
ALTER TABLE STK 
ADD CONSTRAINT FK_STK_KHACHHANG
FOREIGN KEY (MAKH) 
REFERENCES KHACHHANG(MAKH)

GO
ALTER TABLE STK 
ADD CONSTRAINT FK_STK_LOAITK
FOREIGN KEY (MALOAITK) 
REFERENCES LOAITK(MALOAITK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_STK
FOREIGN KEY (MASTK) 
REFERENCES STK(MASTK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_LOAITK
FOREIGN KEY (MALOAITK) 
REFERENCES LOAITK(MALOAITK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_GIAODICHVIEN
FOREIGN KEY (MAGDV) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT CK_GIAODICHVIEN_GIOITINH
CHECK (GIOITINH IN (N'Nam',N'Nữ'))

GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CK_KHACHHANG_GIOITINH
CHECK (GIOITINH IN (N'Nam',N'Nữ'))
