create database QuanLySoTietKiem

go
use QuanLySoTietKiem

go
create table STK
(
	MASTK char(10),
	MAKH char(10),
	MALOAITK char(10),
	NGAYMO	smalldatetime,
	NGAYBD smalldatetime,
	NGAYDH smalldatetime,
	SODU decimal,
	CONSTRAINT PK_STK_MASTK PRIMARY KEY (MASTK)
)

go
create table KHACHHANG
(
	MAKH char(10),
	HOTEN Varchar(40),
	DIACHI Varchar(40),
	SDT Varchar(20),
	GIOITINH nvarchar(3),
	NGAYSINH Smalldatetime,
	CMND Varchar(20),
	CONSTRAINT PK_KHACHHANG_MAKH PRIMARY KEY (MAKH)
)

go
create table GIAODICHVIEN
(
	MAGDV char(10),
	MAPHONG Char(10),
	HOTEN Varchar(40),
	DIACHI Varchar(40),
	SDT Varchar(20),
	GIOITINH nvarchar(3),
	NGAYSINH Smalldatetime,
	CMND Varchar(20),
	MATK Char(10),
	CONSTRAINT PK_GIAODICHVIEN_MAGDV PRIMARY KEY (MAGDV)
)

go
create table PHONGBAN
(
	MAPHONG char(10),
	DIADIEM Varchar(40),
	TRGPHONG Char(10),
	NGAYNC Smalldatetime,
	CONSTRAINT PK_PHONGBAN_MAPHONG PRIMARY KEY (MAPHONG)
)

go
create table QUAYGD
(
	MAQUAY char(10),
	TENQUAY varchar(100),
	CONSTRAINT PK_QUAYGD_MAQUAY PRIMARY KEY (MAQUAY)
)

go
create table LOAITK
(
	MALOAITK char(10),
	TENLOAI varchar(50),
	LAISUAT float,
	KIHAN varchar(50),
	CONSTRAINT PK_LOAITK_MALOAITK PRIMARY KEY (MALOAITK)
)

go
create table GIAODICH
(
	SOGD char(10),
	MAGDV char(10),
	MAKH char(10),
	MAQUAYGD char(10),
	NGAYGD smalldatetime,
	CTGD varchar(50),
	CONSTRAINT PK_GIAODICH_SOGD PRIMARY KEY (SOGD)
)

go
create table ACCOUNT
(
	MATK char(10),
	TAIKHOAN varchar(50),
	MATKHAU varchar(50),
	CONSTRAINT PK_TAIKHOAN_MATK PRIMARY KEY (MATK)
)

go
create table CAPNHAT
(
	MACN char(10),
	MAGDV Char(10),
	MASTK Char(10),
	MALOAITK Char(10),
	NGAYCN Smalldatetime,
	SODU decimal,
	NGAYBD smalldatetime,
	NGAYDH smalldatetime,
	CONSTRAINT PK_CAPNHAT_MACN PRIMARY KEY (MACN)
)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT FK_GIAODICHVIEN_PHONGBAN 
FOREIGN KEY (MAPHONG) 
REFERENCES PHONGBAN(MAPHONG)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT FK_GIAODICHVIEN_TAIKHOAN
FOREIGN KEY (MATK) 
REFERENCES ACCOUNT(MATK)

GO
ALTER TABLE PHONGBAN 
ADD CONSTRAINT FK_PHONGBAN_GIAODICHVIEN
FOREIGN KEY (TRGPHONG) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_GIAODICHVIEN
FOREIGN KEY (MAGDV) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_QUAYGD
FOREIGN KEY (MAQUAYGD) 
REFERENCES QUAYGD(MAQUAY)

GO
ALTER TABLE GIAODICH 
ADD CONSTRAINT FK_GIAODICH_KHACHHANG
FOREIGN KEY (MAKH) 
REFERENCES KHACHHANG(MAKH)

GO
ALTER TABLE STK 
ADD CONSTRAINT FK_STK_KHACHHANG
FOREIGN KEY (MAKH) 
REFERENCES KHACHHANG(MAKH)

GO
ALTER TABLE STK 
ADD CONSTRAINT FK_STK_LOAITK
FOREIGN KEY (MALOAITK) 
REFERENCES LOAITK(MALOAITK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_STK
FOREIGN KEY (MASTK) 
REFERENCES STK(MASTK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_LOAITK
FOREIGN KEY (MALOAITK) 
REFERENCES LOAITK(MALOAITK)

GO
ALTER TABLE CAPNHAT 
ADD CONSTRAINT FK_CAPNHAT_GIAODICHVIEN
FOREIGN KEY (MAGDV) 
REFERENCES GIAODICHVIEN(MAGDV)

GO
ALTER TABLE GIAODICHVIEN 
ADD CONSTRAINT CK_GIAODICHVIEN_GIOITINH
CHECK (GIOITINH IN (N'Nam',N'Nữ'))

GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CK_KHACHHANG_GIOITINH
CHECK (GIOITINH IN (N'Nam',N'Nữ'))

GO
CREATE TRIGGER TG_STK_NGAYMO_SODU
ON STK
FOR INSERT
AS
BEGIN
	DECLARE @NGAYMO smalldatetime, @MAKH CHAR(10), @NGAYSINH SMALLDATETIME, @SODU DECIMAL
	SELECT @NGAYMO = NGAYMO, @MAKH = MAKH, @SODU = SODU
	FROM inserted
	SELECT @NGAYSINH = NGAYSINH
	FROM KHACHHANG
	WHERE MAKH = @MAKH
	IF (@NGAYMO < @NGAYSINH)
	BEGIN
		PRINT N'NGÀY MỞ SỔ PHẢI SAU NGÀY SINH CỦA KHÁCH HÀNG!!!'
		ROLLBACK TRANSACTION
	END
	ELSE IF (@SODU < 1000000)
	BEGIN
		PRINT N'SỐ DƯ PHẢI LỚN HƠN 1 TRIỆU ĐỒNG!!!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'THÊM SỔ TIẾT KIỆM THÀNH CÔNG.'
	END
END

GO
CREATE TRIGGER TG_PHONGBAN_NGAYNC
ON PHONGBAN
FOR INSERT
AS
BEGIN
	DECLARE @NGAYNC smalldatetime, @TRGPHONG CHAR(10), @NGAYSINH smalldatetime

	SELECT @NGAYNC = NGAYNC, @TRGPHONG = TRGPHONG
	FROM inserted

	SELECT @NGAYSINH = NGAYSINH
	FROM GIAODICHVIEN
	WHERE MAGDV = @TRGPHONG

	IF (@NGAYNC < @NGAYSINH)
	BEGIN
		PRINT N'NGÀY NHẬN CHỨC PHẢI LỚN HƠN NGÀY SINH CỦA GIAO DỊCH VIÊN!!!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT N'THÊM TRƯỞNG PHÒNG THÀNH CÔNG.'
	END
END

GO
CREATE TRIGGER TG_CAPNHAT_NGAYCN_SODU
ON CAPNHAT
FOR INSERT
AS
BEGIN
	DECLARE @NGAYCN smalldatetime, @MASTK CHAR(10), @SODU_CN DECIMAL, @SODU_STK DECIMAL, @NGAYDH_STK SMALLDATETIME
	DECLARE @NGAYBD SMALLDATETIME, @NGAYDH_CN SMALLDATETIME, @MALOAITK CHAR(10)

	SELECT @NGAYCN = NGAYCN, @MASTK = MASTK, @SODU_CN = SODU, @MALOAITK = MALOAITK, @NGAYBD = NGAYBD, @NGAYDH_CN = NGAYDH
	FROM inserted

	SELECT @NGAYDH_STK = NGAYDH, @SODU_STK = SODU
	FROM STK
	WHERE MASTK = @MASTK

	IF (@NGAYCN != @NGAYDH_STK)
	BEGIN
		PRINT N'CHƯA ĐẾN KÌ HẠN TÍNH LÃI SUẤT!!!'
		ROLLBACK TRANSACTION
	END
	ELSE IF ((@SODU_CN - @SODU_STK) < 100000)
	BEGIN
		PRINT N'SỐ TIỀN GỬI THÊM PHẢI TỐI THIỂU LÀ MỘT TRĂM NGHÌN ĐỒNG!!!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		update STK
		Set MALOAITK = @MALOAITK, NGAYBD = @NGAYBD, NGAYDH = @NGAYDH_CN, SODU = @SODU_CN
		where MASTK = @MASTK
		PRINT N'CẬP NHẬT THÀNH CÔNG.'
	END
END

